apiVersion: v1
kind: Secret
metadata:
    name: api-secret
    namespace: honarino
type: Opaque
stringData:
    DATABASE_URL: postgresql://postgres:postgres@postgres:5432/api_db
    RUST_LOG: info
    APP_HOST: "0.0.0.0"
    APP_PORT: "8000"
    SERVICE_VERSION: v1
    JWT_SECRET: the_jwt_secret_key
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: VeryStrongPassword123
    MINIO_ENDPOINT: http://minio:9000
    MINIO_PUBLIC_ENDPOINT: /storage
