apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: honarino
type: Opaque
stringData:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: VeryStrongPassword123
    MINIO_ENDPOINT: http://minio:9000
    MINIO_PUBLIC_ENDPOINT: http://honarino.local/
